-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Global exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


title : Translations -> String
title translations =
    t translations "global.title"


login : Translations -> String
login translations =
    t translations "global.login"


register : Translations -> String
register translations =
    t translations "global.register"


username : Translations -> String
username translations =
    t translations "global.username"


password : Translations -> String
password translations =
    t translations "global.password"


dashboard : Translations -> String
dashboard translations =
    t translations "global.dashboard"
