-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Global exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


title : Translations -> String
title translations =
    t translations "global.title"


login : Translations -> String
login translations =
    t translations "global.login"


register : Translations -> String
register translations =
    t translations "global.register"


username : Translations -> String
username translations =
    t translations "global.username"


password : Translations -> String
password translations =
    t translations "global.password"


dashboard : Translations -> String
dashboard translations =
    t translations "global.dashboard"


logout : Translations -> String
logout translations =
    t translations "global.logout"


today : Translations -> String
today translations =
    t translations "global.today"


tomorrow : Translations -> String
tomorrow translations =
    t translations "global.tomorrow"


dayAfterTomorrow : Translations -> String
dayAfterTomorrow translations =
    t translations "global.day_after_tomorrow"


heyUsername : Translations -> String -> String
heyUsername translations user =
    tr translations Curly "global.hey_username" [ ( "user", user ) ]


loading : Translations -> String
loading translations =
    t translations "global.loading"


required : Translations -> String
required translations =
    t translations "global.required"


exampleSubject : Translations -> String
exampleSubject translations =
    t translations "global.example_subject"


submit : Translations -> String
submit translations =
    t translations "global.submit"
