-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Pages.Dashboard exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


moodleIntegration : Translations -> String
moodleIntegration translations =
    t translations "pages.dashboard.moodle_integration"


admin : Translations -> String
admin translations =
    t translations "pages.dashboard.admin"


nothing : Translations -> String
nothing translations =
    t translations "pages.dashboard.nothing"


others : Translations -> String
others translations =
    t translations "pages.dashboard.others"


createAssignments : Translations -> String
createAssignments translations =
    t translations "pages.dashboard.create_assignments"


searchCourses : Translations -> String
searchCourses translations =
    t translations "pages.dashboard.search_courses"


title : Translations -> String
title translations =
    t translations "pages.dashboard.title"


exampleTitle : Translations -> String
exampleTitle translations =
    t translations "pages.dashboard.example_title"


dueDate : Translations -> String
dueDate translations =
    t translations "pages.dashboard.due_date"


dueDateSelectedDateDaysFromNow : Translations -> String -> String
dueDateSelectedDateDaysFromNow translations days =
    tr translations Curly "pages.dashboard.due_date_selected_date_days_from_now" [ ( "days", days ) ]
