-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Pages.Login exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


enterUsername : Translations -> String
enterUsername translations =
    t translations "pages.login.enter_username"


enterPassword : Translations -> String
enterPassword translations =
    t translations "pages.login.enter_password"
