-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Pages.Top exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


aboutTitle : Translations -> String
aboutTitle translations =
    t translations "pages.top.about_title"


aboutContent : Translations -> String
aboutContent translations =
    t translations "pages.top.about_content"
