"""empty message

Revision ID: 29d52835d5d0
Revises: 
Create Date: 2021-01-30 01:24:45.548897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d52835d5d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moodle_cache', sa.Column('assignments_json', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moodle_cache', 'assignments_json')
    # ### end Alembic commands ###
